export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST'
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST'
export const RECEIVE_ARTICLE_LIST_MORE = 'RECEIVE_ARTICLE_LIST_MORE'
export const COUNT = 10

export const OPEN_TO_LOOK_PICTURE = 'OPEN_TO_LOOK_PICTURE'
export const CLOSE_TO_LOOK_PICTURE = 'CLOSE_TO_LOOK_PICTURE'