export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST'
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST'
export const RECEIVE_ARTICLE_LIST_MORE = 'RECEIVE_ARTICLE_LIST_MORE'
export const COUNT = 10

export const SKIP_PAGE = 'SKIP_PAGE'
export const GOBACK_PAGE = 'GOBACK_PAGE'